# Page copy for every language. Not reviewed by native speakers; keep keys identical across languages.
# {n} and {total} in shot_alt are filled in by build_site.py.

EN = dict(
    name="English", dir="ltr", html_lang="en",
    title="IronLog: Workout Tracker",
    desc="IronLog is a fast, simple workout tracker. Log every set in seconds, track your strength, and turn each workout into a shareable card. No account, no ads, 15 languages.",
    og_desc="Log every set in seconds, track your strength, and share every win. No account, no ads, 15 languages.",
    skip="Skip to content", nav_screens="Screens", nav_features="Features", nav_get="Get the app", lang_label="Language",
    appid_sub="Workout tracker for iPhone and Android",
    h1a="Log every set.", h1b="Share every win.",
    lede="IronLog is a fast, simple way to log your workouts, track your strength and turn every session into a card worth sharing. No account to create, no ads in the way.",
    store_get="Get it on", store_dl="Download on the", store_soon="Coming soon to the",
    fact1="No account needed", fact2="No ads", fact3="15 languages",
    screens_h="See it in action", screens_sub="From the first setup to the finished workout card, here's what using IronLog looks like.",
    gallery_label="IronLog screenshots, scroll sideways", shot_alt="IronLog screenshot {n} of {total}",
    features_h="Built for the way you train", features_sub="Everything you need to log, follow and show your training, and nothing you don't.",
    f1h="Log in seconds", f1p="Sets, reps, weight, duration and bodyweight exercises with a tap. The pickers start from your last numbers, and a rest timer is built in.",
    f2h="Your program, your way", f2p="Create your own training days, pair exercises into supersets, and use the built-in exercise library or add your own custom exercises. Give any exercise your own alias, like “BB Bench”, so it's named the way you say it.",
    f3h="See real progress", f3p="Personal records, weekly trends and volume charts, plus body weight and measurements over time, all in one calendar history.",
    f4h="Share cards", f4p="Turn any finished workout into a card with your photo, colours, font and layout, in an Instagram Story style, ready to share or save.",
    f5h="Private by design", f5p="Your data stays on your device. No account, login or cloud needed, with one-file backup and restore and an export of your workout log.",
    f6h="Made for everyone", f6p="Available in 15 languages, with full right-to-left support for Arabic and Urdu.",
    get_h="Get IronLog", get_sub="Scan a code with your phone's camera, or tap a button.",
    android_p="Available now on Google Play.", iphone_soon="On its way to the App Store.", iphone_live="Available now on the App Store.",
    qr_soon="QR code appears when the app goes live",
    qr_alt_play="QR code linking to IronLog on Google Play", qr_alt_apple="QR code linking to IronLog on the App Store",
    foot_privacy="Privacy Policy", foot_terms="Terms of Use", foot_guide="User Guide", foot_contact="Contact",
    home_aria="IronLog home", icon_alt="IronLog app icon",
)

ES = dict(
    name="Español", dir="ltr", html_lang="es",
    title="IronLog: Registro de Gym",
    desc="IronLog es un registro de entrenamientos rápido y sencillo. Registra cada serie en segundos, sigue tu fuerza y convierte cada entrenamiento en una tarjeta para compartir. Sin cuenta, sin anuncios, en 15 idiomas.",
    og_desc="Registra cada serie en segundos, sigue tu fuerza y comparte cada logro. Sin cuenta, sin anuncios, en 15 idiomas.",
    skip="Saltar al contenido", nav_screens="Pantallas", nav_features="Funciones", nav_get="Obtener la app", lang_label="Idioma",
    appid_sub="Registro de entrenamientos para iPhone y Android",
    h1a="Registra cada serie.", h1b="Comparte cada logro.",
    lede="IronLog es una forma rápida y sencilla de registrar tus entrenamientos, seguir tu fuerza y convertir cada sesión en una tarjeta que vale la pena compartir. Sin crear cuenta y sin anuncios por medio.",
    store_get="Disponible en", store_dl="Descárgala en", store_soon="Próximamente en",
    fact1="Sin cuenta", fact2="Sin anuncios", fact3="15 idiomas",
    screens_h="Míralo en acción", screens_sub="Desde la primera configuración hasta la tarjeta del entrenamiento terminado, así se ve usar IronLog.",
    gallery_label="Capturas de pantalla de IronLog, desplázate hacia los lados", shot_alt="Captura de IronLog {n} de {total}",
    features_h="Hecha para tu forma de entrenar", features_sub="Todo lo que necesitas para registrar, seguir y mostrar tu entrenamiento, y nada que sobre.",
    f1h="Registra en segundos", f1p="Series, repeticiones, peso, duración y ejercicios con peso corporal con un toque. Los selectores parten de tus últimos números y hay un temporizador de descanso integrado.",
    f2h="Tu programa, a tu manera", f2p="Crea tus propios días de entrenamiento, une ejercicios en superseries y usa la biblioteca de ejercicios incluida o añade los tuyos. Dale a cualquier ejercicio un alias, como “BB Bench”, para llamarlo como tú lo dices.",
    f3h="Mira tu progreso real", f3p="Récords personales, tendencias semanales y gráficos de volumen, además de peso corporal y medidas a lo largo del tiempo, todo en un historial con calendario.",
    f4h="Tarjetas para compartir", f4p="Convierte cualquier entrenamiento terminado en una tarjeta con tu foto, colores, fuente y diseño, al estilo de una historia de Instagram, lista para compartir o guardar.",
    f5h="Privada por diseño", f5p="Tus datos se quedan en tu dispositivo. No necesitas cuenta, inicio de sesión ni nube, con copia de seguridad y restauración en un solo archivo y exportación de tu registro.",
    f6h="Hecha para todos", f6p="Disponible en 15 idiomas, con compatibilidad total de derecha a izquierda para árabe y urdu.",
    get_h="Consigue IronLog", get_sub="Escanea un código con la cámara de tu teléfono o toca un botón.",
    android_p="Disponible ahora en Google Play.", iphone_soon="Muy pronto en la App Store.", iphone_live="Disponible ahora en la App Store.",
    qr_soon="El código QR aparecerá cuando la app esté disponible",
    qr_alt_play="Código QR que lleva a IronLog en Google Play", qr_alt_apple="Código QR que lleva a IronLog en la App Store",
    foot_privacy="Política de privacidad", foot_terms="Términos de uso", foot_guide="Guía de usuario", foot_contact="Contacto",
    home_aria="Inicio de IronLog", icon_alt="Icono de la app IronLog",
)

FR = dict(
    name="Français", dir="ltr", html_lang="fr",
    title="IronLog : Suivi d'Entraînement",
    desc="IronLog est un suivi d'entraînement rapide et simple. Enregistrez chaque série en quelques secondes, suivez votre force et transformez chaque séance en carte à partager. Sans compte, sans publicité, en 15 langues.",
    og_desc="Enregistrez chaque série en quelques secondes, suivez votre force et partagez chaque victoire. Sans compte, sans publicité, en 15 langues.",
    skip="Aller au contenu", nav_screens="Écrans", nav_features="Fonctionnalités", nav_get="Obtenir l'app", lang_label="Langue",
    appid_sub="Suivi d'entraînement pour iPhone et Android",
    h1a="Enregistrez chaque série.", h1b="Partagez chaque victoire.",
    lede="IronLog est un moyen rapide et simple d'enregistrer vos entraînements, de suivre votre force et de transformer chaque séance en carte qui mérite d'être partagée. Aucun compte à créer, aucune publicité pour vous gêner.",
    store_get="Disponible sur", store_dl="Télécharger dans l'", store_soon="Bientôt sur l'",
    fact1="Aucun compte requis", fact2="Sans publicité", fact3="15 langues",
    screens_h="Voyez-la en action", screens_sub="De la première configuration à la carte d'entraînement terminée, voici à quoi ressemble IronLog.",
    gallery_label="Captures d'écran d'IronLog, faites défiler horizontalement", shot_alt="Capture d'écran IronLog {n} sur {total}",
    features_h="Conçue pour votre façon de vous entraîner", features_sub="Tout ce qu'il faut pour enregistrer, suivre et montrer votre entraînement, rien de superflu.",
    f1h="Enregistrez en quelques secondes", f1p="Séries, répétitions, poids, durée et exercices au poids du corps en un geste. Les sélecteurs partent de vos derniers chiffres, et un minuteur de repos est intégré.",
    f2h="Votre programme, à votre façon", f2p="Créez vos propres jours d'entraînement, associez des exercices en supersets, et utilisez la bibliothèque d'exercices intégrée ou ajoutez les vôtres. Donnez à n'importe quel exercice un alias, comme « BB Bench », pour l'appeler comme vous le dites.",
    f3h="Voyez de vrais progrès", f3p="Records personnels, tendances hebdomadaires et graphiques de volume, plus poids corporel et mensurations au fil du temps, le tout dans un historique en calendrier.",
    f4h="Cartes à partager", f4p="Transformez toute séance terminée en carte avec votre photo, vos couleurs, votre police et votre mise en page, façon story Instagram, prête à partager ou à enregistrer.",
    f5h="Privée par conception", f5p="Vos données restent sur votre appareil. Aucun compte, identifiant ni cloud requis, avec sauvegarde et restauration en un seul fichier et export de votre journal d'entraînement.",
    f6h="Pour tout le monde", f6p="Disponible en 15 langues, avec prise en charge complète de l'écriture de droite à gauche pour l'arabe et l'ourdou.",
    get_h="Obtenir IronLog", get_sub="Scannez un code avec l'appareil photo de votre téléphone, ou touchez un bouton.",
    android_p="Disponible dès maintenant sur Google Play.", iphone_soon="Bientôt sur l'App Store.", iphone_live="Disponible dès maintenant sur l'App Store.",
    qr_soon="Le code QR apparaîtra dès que l'app sera disponible",
    qr_alt_play="Code QR menant à IronLog sur Google Play", qr_alt_apple="Code QR menant à IronLog sur l'App Store",
    foot_privacy="Politique de confidentialité", foot_terms="Conditions d'utilisation", foot_guide="Guide d'utilisation", foot_contact="Contact",
    home_aria="Accueil IronLog", icon_alt="Icône de l'app IronLog",
)

PT = dict(
    name="Português", dir="ltr", html_lang="pt-BR",
    title="IronLog: Rastreador de Treinos",
    desc="O IronLog é um rastreador de treinos rápido e simples. Registre cada série em segundos, acompanhe sua força e transforme cada treino em um cartão para compartilhar. Sem conta, sem anúncios, em 15 idiomas.",
    og_desc="Registre cada série em segundos, acompanhe sua força e compartilhe cada conquista. Sem conta, sem anúncios, em 15 idiomas.",
    skip="Ir para o conteúdo", nav_screens="Telas", nav_features="Recursos", nav_get="Baixar o app", lang_label="Idioma",
    appid_sub="Rastreador de treinos para iPhone e Android",
    h1a="Registre cada série.", h1b="Compartilhe cada conquista.",
    lede="O IronLog é um jeito rápido e simples de registrar seus treinos, acompanhar sua força e transformar cada sessão em um cartão que vale a pena compartilhar. Sem criar conta, sem anúncios no caminho.",
    store_get="Disponível no", store_dl="Baixe na", store_soon="Em breve na",
    fact1="Sem conta", fact2="Sem anúncios", fact3="15 idiomas",
    screens_h="Veja em ação", screens_sub="Da primeira configuração ao cartão do treino finalizado, veja como é usar o IronLog.",
    gallery_label="Capturas de tela do IronLog, role para o lado", shot_alt="Captura de tela {n} de {total} do IronLog",
    features_h="Feito para o seu jeito de treinar", features_sub="Tudo o que você precisa para registrar, acompanhar e mostrar seu treino, e nada além disso.",
    f1h="Registre em segundos", f1p="Séries, repetições, carga, duração e exercícios com o peso do corpo com um toque. Os seletores começam dos seus últimos números e há um cronômetro de descanso integrado.",
    f2h="Seu programa, do seu jeito", f2p="Crie seus próprios dias de treino, una exercícios em super-séries e use a biblioteca de exercícios integrada ou adicione os seus. Dê a qualquer exercício um apelido, como “BB Bench”, para chamá-lo do jeito que você fala.",
    f3h="Veja o progresso real", f3p="Recordes pessoais, tendências semanais e gráficos de volume, além de peso corporal e medidas ao longo do tempo, tudo em um histórico em calendário.",
    f4h="Cartões para compartilhar", f4p="Transforme qualquer treino finalizado em um cartão com sua foto, cores, fonte e layout, no estilo de um Story do Instagram, pronto para compartilhar ou salvar.",
    f5h="Privado por natureza", f5p="Seus dados ficam no seu dispositivo. Sem conta, login ou nuvem, com backup e restauração em um único arquivo e exportação do seu registro de treinos.",
    f6h="Feito para todos", f6p="Disponível em 15 idiomas, com suporte completo da direita para a esquerda para árabe e urdu.",
    get_h="Baixe o IronLog", get_sub="Escaneie um código com a câmera do celular ou toque em um botão.",
    android_p="Disponível agora no Google Play.", iphone_soon="A caminho da App Store.", iphone_live="Disponível agora na App Store.",
    qr_soon="O código QR aparece quando o app estiver disponível",
    qr_alt_play="Código QR que leva ao IronLog no Google Play", qr_alt_apple="Código QR que leva ao IronLog na App Store",
    foot_privacy="Política de Privacidade", foot_terms="Termos de Uso", foot_guide="Guia do Usuário", foot_contact="Contato",
    home_aria="Início do IronLog", icon_alt="Ícone do app IronLog",
)

DE = dict(
    name="Deutsch", dir="ltr", html_lang="de",
    title="IronLog: Workout Tracker",
    desc="IronLog ist ein schneller, einfacher Workout-Tracker. Logge jeden Satz in Sekunden, verfolge deine Kraft und verwandle jedes Training in eine teilbare Karte. Ohne Konto, ohne Werbung, in 15 Sprachen.",
    og_desc="Logge jeden Satz in Sekunden, verfolge deine Kraft und teile jeden Erfolg. Ohne Konto, ohne Werbung, in 15 Sprachen.",
    skip="Zum Inhalt springen", nav_screens="Screens", nav_features="Funktionen", nav_get="App holen", lang_label="Sprache",
    appid_sub="Workout-Tracker für iPhone und Android",
    h1a="Logge jeden Satz.", h1b="Teile jeden Erfolg.",
    lede="IronLog ist der schnelle, einfache Weg, deine Workouts zu loggen, deine Kraft zu verfolgen und jede Einheit in eine Karte zu verwandeln, die man gern teilt. Kein Konto nötig, keine Werbung im Weg.",
    store_get="Jetzt bei", store_dl="Laden im", store_soon="Bald im",
    fact1="Kein Konto nötig", fact2="Keine Werbung", fact3="15 Sprachen",
    screens_h="Sieh es in Aktion", screens_sub="Von der ersten Einrichtung bis zur fertigen Workout-Karte: So fühlt sich IronLog an.",
    gallery_label="IronLog-Screenshots, seitlich scrollen", shot_alt="IronLog-Screenshot {n} von {total}",
    features_h="Gebaut für dein Training", features_sub="Alles, was du brauchst, um dein Training zu loggen, zu verfolgen und zu zeigen, und nichts, was du nicht brauchst.",
    f1h="In Sekunden loggen", f1p="Sätze, Wiederholungen, Gewicht, Dauer und Körpergewichtsübungen mit einem Tippen. Die Auswahl startet bei deinen letzten Werten, und ein Pausentimer ist eingebaut.",
    f2h="Dein Plan, dein Weg", f2p="Erstelle eigene Trainingstage, kombiniere Übungen zu Supersätzen und nutze die integrierte Übungsbibliothek oder füge eigene Übungen hinzu. Gib jeder Übung einen Alias, etwa „BB Bench“, damit sie so heißt, wie du sie nennst.",
    f3h="Echten Fortschritt sehen", f3p="Persönliche Rekorde, Wochentrends und Volumendiagramme, dazu Körpergewicht und Maße im Zeitverlauf, alles in einem Kalenderverlauf.",
    f4h="Teilbare Karten", f4p="Verwandle jedes beendete Workout in eine Karte mit deinem Foto, deinen Farben, deiner Schrift und deinem Layout, im Stil einer Instagram-Story, bereit zum Teilen oder Speichern.",
    f5h="Privat von Grund auf", f5p="Deine Daten bleiben auf deinem Gerät. Kein Konto, kein Login, keine Cloud nötig, mit Backup und Wiederherstellung in einer Datei und Export deines Trainingsprotokolls.",
    f6h="Für alle gemacht", f6p="In 15 Sprachen verfügbar, mit voller Rechts-nach-links-Unterstützung für Arabisch und Urdu.",
    get_h="Hol dir IronLog", get_sub="Scanne einen Code mit der Handykamera oder tippe auf einen Button.",
    android_p="Jetzt bei Google Play erhältlich.", iphone_soon="Bald im App Store.", iphone_live="Jetzt im App Store erhältlich.",
    qr_soon="Der QR-Code erscheint, sobald die App verfügbar ist",
    qr_alt_play="QR-Code zu IronLog bei Google Play", qr_alt_apple="QR-Code zu IronLog im App Store",
    foot_privacy="Datenschutz", foot_terms="Nutzungsbedingungen", foot_guide="Benutzerhandbuch", foot_contact="Kontakt",
    home_aria="IronLog Startseite", icon_alt="IronLog App-Symbol",
)

RU = dict(
    name="Русский", dir="ltr", html_lang="ru",
    title="IronLog: Трекер Тренировок",
    desc="IronLog — быстрый и простой трекер тренировок. Записывай каждый подход за секунды, следи за силой и превращай тренировки в карточки, которыми можно поделиться. Без аккаунта, без рекламы, на 15 языках.",
    og_desc="Записывай каждый подход за секунды, следи за силой и делись каждой победой. Без аккаунта, без рекламы, на 15 языках.",
    skip="Перейти к содержимому", nav_screens="Экраны", nav_features="Возможности", nav_get="Скачать", lang_label="Язык",
    appid_sub="Трекер тренировок для iPhone и Android",
    h1a="Записывай каждый подход.", h1b="Делись каждой победой.",
    lede="IronLog — быстрый и простой способ записывать тренировки, следить за силой и превращать каждую тренировку в карточку, которой хочется поделиться. Не нужно создавать аккаунт, и никакой рекламы.",
    store_get="Доступно в", store_dl="Загрузите в", store_soon="Скоро в",
    fact1="Без аккаунта", fact2="Без рекламы", fact3="15 языков",
    screens_h="Посмотри в действии", screens_sub="От первой настройки до готовой карточки тренировки — вот как выглядит IronLog.",
    gallery_label="Скриншоты IronLog, листай вбок", shot_alt="Скриншот IronLog {n} из {total}",
    features_h="Создано под твои тренировки", features_sub="Всё, что нужно, чтобы записывать, отслеживать и показывать свои тренировки, и ничего лишнего.",
    f1h="Записывай за секунды", f1p="Подходы, повторы, вес, время и упражнения с собственным весом одним касанием. Выбор значений начинается с твоих прошлых результатов, а таймер отдыха уже встроен.",
    f2h="Твоя программа, твои правила", f2p="Создавай свои тренировочные дни, объединяй упражнения в суперсеты и пользуйся встроенной библиотекой упражнений или добавляй свои. Дай любому упражнению псевдоним, например «BB Bench», чтобы оно называлось так, как ты его говоришь.",
    f3h="Смотри реальный прогресс", f3p="Личные рекорды, недельные тренды и графики объёма, а также вес тела и замеры со временем, всё в одной истории с календарём.",
    f4h="Карточки для публикации", f4p="Преврати любую завершённую тренировку в карточку со своим фото, цветами, шрифтом и макетом в стиле сторис Instagram, готовую к публикации или сохранению.",
    f5h="Конфиденциальность по умолчанию", f5p="Твои данные остаются на твоём устройстве. Не нужны ни аккаунт, ни вход, ни облако; есть резервная копия и восстановление одним файлом и экспорт журнала тренировок.",
    f6h="Для всех", f6p="Доступно на 15 языках, с полной поддержкой письма справа налево для арабского и урду.",
    get_h="Скачай IronLog", get_sub="Наведи камеру телефона на код или нажми на кнопку.",
    android_p="Уже доступно в Google Play.", iphone_soon="Скоро в App Store.", iphone_live="Уже доступно в App Store.",
    qr_soon="QR-код появится, когда приложение станет доступно",
    qr_alt_play="QR-код со ссылкой на IronLog в Google Play", qr_alt_apple="QR-код со ссылкой на IronLog в App Store",
    foot_privacy="Политика конфиденциальности", foot_terms="Условия использования", foot_guide="Руководство пользователя", foot_contact="Связаться",
    home_aria="IronLog, главная", icon_alt="Значок приложения IronLog",
)

AR = dict(
    name="العربية", dir="rtl", html_lang="ar",
    title="IronLog: متتبع التمارين",
    desc="IronLog تطبيق سريع وبسيط لتتبع التمارين. سجّل كل مجموعة في ثوانٍ، وتتبّع قوتك، وحوّل كل تمرين إلى بطاقة قابلة للمشاركة. بلا حساب وبلا إعلانات وبـ15 لغة.",
    og_desc="سجّل كل مجموعة في ثوانٍ، وتتبّع قوتك، وشارك كل إنجاز. بلا حساب وبلا إعلانات وبـ15 لغة.",
    skip="انتقل إلى المحتوى", nav_screens="الشاشات", nav_features="المزايا", nav_get="حمّل التطبيق", lang_label="اللغة",
    appid_sub="متتبع تمارين لآيفون وأندرويد",
    h1a="سجّل كل مجموعة.", h1b="شارك كل إنجاز.",
    lede="IronLog طريقة سريعة وبسيطة لتسجيل تمارينك وتتبع قوتك وتحويل كل جلسة إلى بطاقة تستحق المشاركة. لا حاجة لإنشاء حساب، ولا إعلانات تزعجك.",
    store_get="احصل عليه من", store_dl="حمّله من", store_soon="قريبًا على",
    fact1="بلا حاجة لحساب", fact2="بلا إعلانات", fact3="15 لغة",
    screens_h="شاهده أثناء العمل", screens_sub="من الإعداد الأول إلى بطاقة التمرين الجاهزة، هكذا يبدو استخدام IronLog.",
    gallery_label="لقطات شاشة IronLog، مرّر جانبيًا", shot_alt="لقطة شاشة IronLog رقم {n} من {total}",
    features_h="مصمم لطريقة تدريبك", features_sub="كل ما تحتاجه لتسجيل تدريبك ومتابعته وعرضه، ولا شيء زائد.",
    f1h="سجّل في ثوانٍ", f1p="المجموعات والتكرارات والوزن والمدة وتمارين وزن الجسم بلمسة واحدة. تبدأ المحددات من أرقامك الأخيرة، ومؤقت الراحة مدمج.",
    f2h="برنامجك بطريقتك", f2p="أنشئ أيام تدريبك الخاصة، واجمع التمارين في مجموعات مركبة (سوبرست)، واستخدم مكتبة التمارين المدمجة أو أضف تمارينك. امنح أي تمرين اسمًا بديلًا، مثل “BB Bench”، ليحمل الاسم الذي تقوله أنت.",
    f3h="شاهد تقدمك الحقيقي", f3p="الأرقام القياسية الشخصية والاتجاهات الأسبوعية ورسوم الحجم، إضافة إلى وزن الجسم والقياسات عبر الوقت، كلها في سجل واحد بتقويم.",
    f4h="بطاقات المشاركة", f4p="حوّل أي تمرين منتهٍ إلى بطاقة بصورتك وألوانك وخطك وتخطيطك، بأسلوب قصص إنستغرام، جاهزة للمشاركة أو الحفظ.",
    f5h="خصوصية بالتصميم", f5p="بياناتك تبقى على جهازك. لا حاجة إلى حساب أو تسجيل دخول أو سحابة، مع نسخ احتياطي واستعادة بملف واحد وتصدير لسجل تمارينك.",
    f6h="للجميع", f6p="متوفر بـ15 لغة، مع دعم كامل للكتابة من اليمين إلى اليسار للعربية والأردية.",
    get_h="احصل على IronLog", get_sub="امسح الرمز بكاميرا هاتفك، أو اضغط على زر.",
    android_p="متوفر الآن على Google Play.", iphone_soon="قريبًا على App Store.", iphone_live="متوفر الآن على App Store.",
    qr_soon="يظهر رمز QR عندما يصبح التطبيق متاحًا",
    qr_alt_play="رمز QR يؤدي إلى IronLog على Google Play", qr_alt_apple="رمز QR يؤدي إلى IronLog على App Store",
    foot_privacy="سياسة الخصوصية", foot_terms="شروط الاستخدام", foot_guide="دليل المستخدم", foot_contact="تواصل معنا",
    home_aria="الصفحة الرئيسية لـ IronLog", icon_alt="أيقونة تطبيق IronLog",
)

HI = dict(
    name="हिन्दी", dir="ltr", html_lang="hi",
    title="IronLog: वर्कआउट ट्रैकर",
    desc="IronLog एक तेज़ और आसान वर्कआउट ट्रैकर है। हर सेट सेकंडों में लॉग करें, अपनी ताकत ट्रैक करें और हर वर्कआउट को शेयर करने लायक कार्ड बनाएं। बिना अकाउंट, बिना विज्ञापन, 15 भाषाओं में।",
    og_desc="हर सेट सेकंडों में लॉग करें, अपनी ताकत ट्रैक करें और हर जीत शेयर करें। बिना अकाउंट, बिना विज्ञापन, 15 भाषाओं में।",
    skip="मुख्य सामग्री पर जाएं", nav_screens="स्क्रीन", nav_features="फ़ीचर", nav_get="ऐप पाएं", lang_label="भाषा",
    appid_sub="iPhone और Android के लिए वर्कआउट ट्रैकर",
    h1a="हर सेट लॉग करें।", h1b="हर जीत शेयर करें।",
    lede="IronLog आपके वर्कआउट लॉग करने, ताकत ट्रैक करने और हर सेशन को शेयर करने लायक कार्ड बनाने का तेज़ और आसान तरीका है। न अकाउंट बनाना है, न विज्ञापन बीच में आते हैं।",
    store_get="इस पर पाएं", store_dl="इससे डाउनलोड करें", store_soon="जल्द आ रहा है",
    fact1="अकाउंट की ज़रूरत नहीं", fact2="कोई विज्ञापन नहीं", fact3="15 भाषाएं",
    screens_h="इसे काम करते देखें", screens_sub="पहले सेटअप से लेकर तैयार वर्कआउट कार्ड तक, IronLog इस्तेमाल करना ऐसा दिखता है।",
    gallery_label="IronLog स्क्रीनशॉट, साइड में स्क्रॉल करें", shot_alt="IronLog स्क्रीनशॉट {n}/{total}",
    features_h="आपके ट्रेनिंग के तरीके के लिए बना", features_sub="लॉग करने, फ़ॉलो करने और अपनी ट्रेनिंग दिखाने के लिए ज़रूरी सब कुछ, और कुछ फ़ालतू नहीं।",
    f1h="सेकंडों में लॉग करें", f1p="सेट, रेप्स, वज़न, अवधि और बॉडीवेट एक्सरसाइज़ बस एक टैप में। पिकर आपके पिछले नंबरों से शुरू होते हैं, और रेस्ट टाइमर पहले से मौजूद है।",
    f2h="आपका प्रोग्राम, आपके तरीके से", f2p="अपने ट्रेनिंग डे बनाएं, एक्सरसाइज़ को सुपरसेट में जोड़ें, और बिल्ट-इन एक्सरसाइज़ लाइब्रेरी इस्तेमाल करें या अपनी कस्टम एक्सरसाइज़ जोड़ें। किसी भी एक्सरसाइज़ को अपना उपनाम दें, जैसे “BB Bench”, ताकि वह उसी नाम से दिखे जो आप बोलते हैं।",
    f3h="असली प्रगति देखें", f3p="पर्सनल रिकॉर्ड, साप्ताहिक ट्रेंड और वॉल्यूम चार्ट, साथ में समय के साथ शरीर का वज़न और माप, सब एक कैलेंडर हिस्ट्री में।",
    f4h="शेयर कार्ड", f4p="किसी भी पूरे हुए वर्कआउट को अपनी फ़ोटो, रंग, फ़ॉन्ट और लेआउट वाले कार्ड में बदलें, इंस्टाग्राम स्टोरी स्टाइल में, शेयर या सेव करने के लिए तैयार।",
    f5h="डिज़ाइन से ही प्राइवेट", f5p="आपका डेटा आपके डिवाइस पर ही रहता है। न अकाउंट, न लॉगिन, न क्लाउड चाहिए; एक फ़ाइल में बैकअप और रिस्टोर, और वर्कआउट लॉग का एक्सपोर्ट भी।",
    f6h="सबके लिए बना", f6p="15 भाषाओं में उपलब्ध, अरबी और उर्दू के लिए दाएं से बाएं लिखने का पूरा सपोर्ट।",
    get_h="IronLog पाएं", get_sub="अपने फ़ोन के कैमरे से कोड स्कैन करें, या बटन पर टैप करें।",
    android_p="अब Google Play पर उपलब्ध है।", iphone_soon="App Store पर जल्द आ रहा है।", iphone_live="अब App Store पर उपलब्ध है।",
    qr_soon="ऐप लाइव होने पर QR कोड यहाँ दिखेगा",
    qr_alt_play="Google Play पर IronLog का QR कोड", qr_alt_apple="App Store पर IronLog का QR कोड",
    foot_privacy="प्राइवेसी पॉलिसी", foot_terms="उपयोग की शर्तें", foot_guide="यूज़र गाइड", foot_contact="संपर्क करें",
    home_aria="IronLog होम", icon_alt="IronLog ऐप आइकन",
)

BN = dict(
    name="বাংলা", dir="ltr", html_lang="bn",
    title="IronLog: ওয়ার্কআউট ট্র্যাকার",
    desc="IronLog একটি দ্রুত ও সহজ ওয়ার্কআউট ট্র্যাকার। প্রতিটি সেট কয়েক সেকেন্ডে লগ করুন, আপনার শক্তি ট্র্যাক করুন এবং প্রতিটি ওয়ার্কআউটকে শেয়ার করার মতো কার্ডে বদলে দিন। অ্যাকাউন্ট ছাড়া, বিজ্ঞাপন ছাড়া, ১৫টি ভাষায়।",
    og_desc="প্রতিটি সেট কয়েক সেকেন্ডে লগ করুন, আপনার শক্তি ট্র্যাক করুন এবং প্রতিটি জয় শেয়ার করুন। অ্যাকাউন্ট ছাড়া, বিজ্ঞাপন ছাড়া, ১৫টি ভাষায়।",
    skip="মূল অংশে যান", nav_screens="স্ক্রিন", nav_features="ফিচার", nav_get="অ্যাপ নিন", lang_label="ভাষা",
    appid_sub="iPhone ও Android-এর জন্য ওয়ার্কআউট ট্র্যাকার",
    h1a="প্রতিটি সেট লগ করুন।", h1b="প্রতিটি জয় শেয়ার করুন।",
    lede="IronLog আপনার ওয়ার্কআউট লগ করার, শক্তি ট্র্যাক করার এবং প্রতিটি সেশনকে শেয়ার করার মতো কার্ডে বদলে দেওয়ার দ্রুত ও সহজ উপায়। অ্যাকাউন্ট খুলতে হয় না, বিজ্ঞাপনও বাধা দেয় না।",
    store_get="পাওয়া যাচ্ছে", store_dl="ডাউনলোড করুন", store_soon="শীঘ্রই আসছে",
    fact1="অ্যাকাউন্ট লাগে না", fact2="কোনো বিজ্ঞাপন নেই", fact3="১৫টি ভাষা",
    screens_h="কাজ করতে দেখুন", screens_sub="প্রথম সেটআপ থেকে সম্পূর্ণ ওয়ার্কআউট কার্ড পর্যন্ত, IronLog ব্যবহার করতে এমন লাগে।",
    gallery_label="IronLog স্ক্রিনশট, পাশে স্ক্রল করুন", shot_alt="IronLog স্ক্রিনশট {n}/{total}",
    features_h="আপনার ট্রেনিংয়ের ধরনের জন্য তৈরি", features_sub="ট্রেনিং লগ করা, অনুসরণ করা ও দেখানোর জন্য যা দরকার সবই আছে, বাড়তি কিছু নেই।",
    f1h="কয়েক সেকেন্ডে লগ করুন", f1p="সেট, রেপ, ওজন, সময়কাল ও বডিওয়েট ব্যায়াম এক ট্যাপেই। পিকারগুলো আপনার শেষ সংখ্যা থেকে শুরু হয়, আর রেস্ট টাইমার আগে থেকেই আছে।",
    f2h="আপনার প্রোগ্রাম, আপনার মতো", f2p="নিজের ট্রেনিং ডে তৈরি করুন, ব্যায়াম জুড়ে সুপারসেট বানান, আর বিল্ট-ইন ব্যায়াম লাইব্রেরি ব্যবহার করুন বা নিজের কাস্টম ব্যায়াম যোগ করুন। যেকোনো ব্যায়ামকে নিজের ডাকনাম দিন, যেমন “BB Bench”, যাতে সেটি আপনি যেভাবে বলেন সেভাবেই থাকে।",
    f3h="আসল অগ্রগতি দেখুন", f3p="ব্যক্তিগত রেকর্ড, সাপ্তাহিক প্রবণতা ও ভলিউম চার্ট, সঙ্গে সময়ের সাথে শরীরের ওজন ও মাপ, সবই এক ক্যালেন্ডার হিস্ট্রিতে।",
    f4h="শেয়ার কার্ড", f4p="যেকোনো শেষ হওয়া ওয়ার্কআউটকে আপনার ছবি, রং, ফন্ট ও লেআউটসহ কার্ডে বদলে নিন, ইনস্টাগ্রাম স্টোরি স্টাইলে, শেয়ার বা সেভ করার জন্য তৈরি।",
    f5h="ডিজাইনেই ব্যক্তিগত", f5p="আপনার ডেটা আপনার ডিভাইসেই থাকে। অ্যাকাউন্ট, লগইন বা ক্লাউড লাগে না; এক ফাইলে ব্যাকআপ ও রিস্টোর এবং ওয়ার্কআউট লগ এক্সপোর্ট করার সুবিধা আছে।",
    f6h="সবার জন্য তৈরি", f6p="১৫টি ভাষায় পাওয়া যায়, আরবি ও উর্দুর জন্য ডান থেকে বাঁ দিকে লেখার পূর্ণ সমর্থনসহ।",
    get_h="IronLog নিন", get_sub="ফোনের ক্যামেরা দিয়ে কোড স্ক্যান করুন, অথবা একটি বোতামে ট্যাপ করুন।",
    android_p="এখন Google Play-তে পাওয়া যাচ্ছে।", iphone_soon="শীঘ্রই App Store-এ আসছে।", iphone_live="এখন App Store-এ পাওয়া যাচ্ছে।",
    qr_soon="অ্যাপ চালু হলে QR কোড এখানে দেখা যাবে",
    qr_alt_play="Google Play-তে IronLog-এর QR কোড", qr_alt_apple="App Store-এ IronLog-এর QR কোড",
    foot_privacy="গোপনীয়তা নীতি", foot_terms="ব্যবহারের শর্তাবলি", foot_guide="ব্যবহারকারী নির্দেশিকা", foot_contact="যোগাযোগ",
    home_aria="IronLog হোম", icon_alt="IronLog অ্যাপ আইকন",
)

ID = dict(
    name="Bahasa Indonesia", dir="ltr", html_lang="id",
    title="IronLog: Pelacak Latihan",
    desc="IronLog adalah pelacak latihan yang cepat dan sederhana. Catat setiap set dalam hitungan detik, pantau kekuatanmu, dan ubah setiap latihan jadi kartu yang bisa dibagikan. Tanpa akun, tanpa iklan, dalam 15 bahasa.",
    og_desc="Catat setiap set dalam hitungan detik, pantau kekuatanmu, dan bagikan setiap pencapaian. Tanpa akun, tanpa iklan, dalam 15 bahasa.",
    skip="Langsung ke konten", nav_screens="Layar", nav_features="Fitur", nav_get="Dapatkan aplikasi", lang_label="Bahasa",
    appid_sub="Pelacak latihan untuk iPhone dan Android",
    h1a="Catat setiap set.", h1b="Bagikan setiap pencapaian.",
    lede="IronLog adalah cara cepat dan sederhana untuk mencatat latihanmu, memantau kekuatanmu, dan mengubah setiap sesi jadi kartu yang layak dibagikan. Tidak perlu membuat akun, tidak ada iklan yang mengganggu.",
    store_get="Dapatkan di", store_dl="Unduh di", store_soon="Segera hadir di",
    fact1="Tanpa akun", fact2="Tanpa iklan", fact3="15 bahasa",
    screens_h="Lihat cara kerjanya", screens_sub="Dari pengaturan awal sampai kartu latihan yang sudah jadi, begini rasanya memakai IronLog.",
    gallery_label="Tangkapan layar IronLog, geser ke samping", shot_alt="Tangkapan layar IronLog {n} dari {total}",
    features_h="Dibuat untuk caramu berlatih", features_sub="Semua yang kamu perlukan untuk mencatat, mengikuti, dan memamerkan latihanmu, tanpa yang tidak perlu.",
    f1h="Catat dalam hitungan detik", f1p="Set, repetisi, beban, durasi, dan latihan berat badan hanya dengan satu ketukan. Pemilih angka dimulai dari angka terakhirmu, dan timer istirahat sudah tersedia.",
    f2h="Programmu, caramu", f2p="Buat hari latihanmu sendiri, gabungkan latihan jadi superset, lalu pakai pustaka latihan bawaan atau tambahkan latihan buatanmu sendiri. Beri nama alias untuk latihan apa pun, seperti “BB Bench”, agar disebut sesuai caramu menyebutnya.",
    f3h="Lihat kemajuan nyata", f3p="Rekor pribadi, tren mingguan, dan grafik volume, plus berat badan dan ukuran tubuh dari waktu ke waktu, semuanya dalam satu riwayat kalender.",
    f4h="Kartu bagikan", f4p="Ubah latihan yang sudah selesai jadi kartu dengan fotomu, warna, font, dan tata letak sendiri, bergaya Story Instagram, siap dibagikan atau disimpan.",
    f5h="Privat sejak awal", f5p="Datamu tetap di perangkatmu. Tanpa akun, login, atau cloud, dengan cadangan dan pemulihan dalam satu file serta ekspor catatan latihanmu.",
    f6h="Dibuat untuk semua", f6p="Tersedia dalam 15 bahasa, dengan dukungan penuh kanan-ke-kiri untuk bahasa Arab dan Urdu.",
    get_h="Dapatkan IronLog", get_sub="Pindai kode dengan kamera ponselmu, atau ketuk sebuah tombol.",
    android_p="Sudah tersedia di Google Play.", iphone_soon="Segera hadir di App Store.", iphone_live="Sudah tersedia di App Store.",
    qr_soon="Kode QR muncul saat aplikasi sudah tersedia",
    qr_alt_play="Kode QR menuju IronLog di Google Play", qr_alt_apple="Kode QR menuju IronLog di App Store",
    foot_privacy="Kebijakan Privasi", foot_terms="Ketentuan Penggunaan", foot_guide="Panduan Pengguna", foot_contact="Kontak",
    home_aria="Beranda IronLog", icon_alt="Ikon aplikasi IronLog",
)

JA = dict(
    name="日本語", dir="ltr", html_lang="ja",
    title="IronLog: ワークアウトトラッカー",
    desc="IronLogは、すばやくシンプルなワークアウトトラッカーです。1セットを数秒で記録し、筋力を管理して、トレーニングをシェアできるカードにしましょう。アカウント不要、広告なし、15言語対応。",
    og_desc="1セットを数秒で記録し、筋力を管理して、成果をシェア。アカウント不要、広告なし、15言語対応。",
    skip="本文へ移動", nav_screens="画面", nav_features="機能", nav_get="アプリを入手", lang_label="言語",
    appid_sub="iPhone・Android対応のワークアウトトラッカー",
    h1a="すべてのセットを記録。", h1b="すべての成果をシェア。",
    lede="IronLogは、トレーニングの記録、筋力の管理、そして毎回のセッションをシェアしたくなるカードにするための、すばやくシンプルな方法です。アカウント登録は不要で、広告に邪魔されることもありません。",
    store_get="入手はこちら", store_dl="ダウンロードはこちら", store_soon="まもなく登場",
    fact1="アカウント不要", fact2="広告なし", fact3="15言語",
    screens_h="実際の画面を見る", screens_sub="最初のセットアップから完成したワークアウトカードまで、IronLogの使い心地をご覧ください。",
    gallery_label="IronLogのスクリーンショット、横にスクロール", shot_alt="IronLogのスクリーンショット {n}/{total}",
    features_h="あなたのトレーニングのために", features_sub="トレーニングの記録、確認、シェアに必要なものだけを揃えました。",
    f1h="数秒で記録", f1p="セット、レップ、重量、時間、自重エクササイズをワンタップで。ピッカーは前回の数値から始まり、休憩タイマーも内蔵しています。",
    f2h="自分だけのプログラム", f2p="トレーニング日を自由に作成し、種目をスーパーセットにまとめ、内蔵の種目ライブラリを使うか、独自の種目を追加できます。どの種目にも「BB Bench」のようなエイリアスを付けて、普段の呼び方で使えます。",
    f3h="本当の成長が見える", f3p="自己ベスト、週ごとの傾向、ボリュームのグラフに加え、体重や体の各部位のサイズの推移も。すべてカレンダー形式の履歴で確認できます。",
    f4h="シェアカード", f4p="完了したワークアウトを、写真、色、フォント、レイアウトを選んで、Instagramストーリーズ風のカードに。そのままシェアも保存もできます。",
    f5h="プライバシー重視の設計", f5p="データは端末の中だけに保存されます。アカウント、ログイン、クラウドは不要。1つのファイルでバックアップと復元ができ、ワークアウト記録の書き出しにも対応します。",
    f6h="みんなのために", f6p="15言語に対応し、アラビア語とウルドゥー語の右から左への表示にも完全対応しています。",
    get_h="IronLogを入手", get_sub="スマートフォンのカメラでコードを読み取るか、ボタンをタップしてください。",
    android_p="Google Playで配信中です。", iphone_soon="App Storeでもまもなく登場します。", iphone_live="App Storeで配信中です。",
    qr_soon="アプリの公開後にQRコードが表示されます",
    qr_alt_play="Google PlayのIronLogへのQRコード", qr_alt_apple="App StoreのIronLogへのQRコード",
    foot_privacy="プライバシーポリシー", foot_terms="利用規約", foot_guide="ユーザーガイド", foot_contact="お問い合わせ",
    home_aria="IronLog ホーム", icon_alt="IronLogアプリのアイコン",
)

KO = dict(
    name="한국어", dir="ltr", html_lang="ko",
    title="IronLog: 헬스 기록",
    desc="IronLog는 빠르고 간단한 운동 기록 앱입니다. 세트를 몇 초 만에 기록하고, 근력을 추적하고, 모든 운동을 공유할 수 있는 카드로 만드세요. 계정 없음, 광고 없음, 15개 언어 지원.",
    og_desc="세트를 몇 초 만에 기록하고, 근력을 추적하고, 모든 성과를 공유하세요. 계정 없음, 광고 없음, 15개 언어 지원.",
    skip="본문으로 건너뛰기", nav_screens="화면", nav_features="기능", nav_get="앱 받기", lang_label="언어",
    appid_sub="iPhone 및 Android용 운동 기록 앱",
    h1a="모든 세트를 기록하세요.", h1b="모든 성과를 공유하세요.",
    lede="IronLog는 운동을 기록하고, 근력을 추적하고, 매 세션을 공유하고 싶은 카드로 만드는 빠르고 간단한 방법입니다. 계정을 만들 필요도, 방해하는 광고도 없습니다.",
    store_get="다음에서 받기", store_dl="다음에서 다운로드", store_soon="곧 출시",
    fact1="계정 필요 없음", fact2="광고 없음", fact3="15개 언어",
    screens_h="실제 화면 보기", screens_sub="첫 설정부터 완성된 운동 카드까지, IronLog를 사용하는 모습입니다.",
    gallery_label="IronLog 스크린샷, 옆으로 스크롤", shot_alt="IronLog 스크린샷 {n}/{total}",
    features_h="나만의 운동 방식에 맞춰", features_sub="운동을 기록하고, 따라가고, 보여주는 데 필요한 모든 것, 불필요한 것은 없습니다.",
    f1h="몇 초 만에 기록", f1p="세트, 횟수, 무게, 시간, 맨몸 운동을 한 번의 탭으로. 선택기는 지난 기록에서 시작하고, 휴식 타이머도 기본 제공됩니다.",
    f2h="나만의 프로그램", f2p="나만의 운동 요일을 만들고, 운동을 슈퍼세트로 묶고, 기본 운동 라이브러리를 쓰거나 직접 운동을 추가하세요. 어떤 운동에든 “BB Bench” 같은 별칭을 붙여 평소 부르는 이름으로 쓸 수 있습니다.",
    f3h="진짜 성장 확인", f3p="개인 최고 기록, 주간 추세, 볼륨 차트와 함께 시간에 따른 체중과 신체 치수도 한눈에. 모두 달력형 기록에서 볼 수 있습니다.",
    f4h="공유 카드", f4p="완료한 운동을 내 사진, 색상, 글꼴, 레이아웃으로 꾸민 인스타그램 스토리 스타일 카드로 만들어 바로 공유하거나 저장하세요.",
    f5h="처음부터 프라이버시", f5p="데이터는 내 기기에만 저장됩니다. 계정, 로그인, 클라우드가 필요 없으며, 파일 하나로 백업과 복원, 운동 기록 내보내기도 지원합니다.",
    f6h="모두를 위한 앱", f6p="15개 언어를 지원하며, 아랍어와 우르두어의 오른쪽에서 왼쪽 표기를 완벽하게 지원합니다.",
    get_h="IronLog 받기", get_sub="휴대폰 카메라로 코드를 스캔하거나 버튼을 탭하세요.",
    android_p="지금 Google Play에서 만나보세요.", iphone_soon="App Store에도 곧 출시됩니다.", iphone_live="지금 App Store에서 만나보세요.",
    qr_soon="앱이 출시되면 QR 코드가 표시됩니다",
    qr_alt_play="Google Play의 IronLog로 연결되는 QR 코드", qr_alt_apple="App Store의 IronLog로 연결되는 QR 코드",
    foot_privacy="개인정보 처리방침", foot_terms="이용약관", foot_guide="사용자 가이드", foot_contact="문의",
    home_aria="IronLog 홈", icon_alt="IronLog 앱 아이콘",
)

TR = dict(
    name="Türkçe", dir="ltr", html_lang="tr",
    title="IronLog: Antrenman Takibi",
    desc="IronLog hızlı ve basit bir antrenman takip uygulamasıdır. Her seti saniyeler içinde kaydet, gücünü takip et ve her antrenmanı paylaşılabilir bir karta dönüştür. Hesap yok, reklam yok, 15 dilde.",
    og_desc="Her seti saniyeler içinde kaydet, gücünü takip et ve her başarını paylaş. Hesap yok, reklam yok, 15 dilde.",
    skip="İçeriğe geç", nav_screens="Ekranlar", nav_features="Özellikler", nav_get="Uygulamayı al", lang_label="Dil",
    appid_sub="iPhone ve Android için antrenman takibi",
    h1a="Her seti kaydet.", h1b="Her başarını paylaş.",
    lede="IronLog, antrenmanlarını kaydetmenin, gücünü takip etmenin ve her seansı paylaşmaya değer bir karta dönüştürmenin hızlı ve basit yolu. Hesap açmana gerek yok, araya giren reklam da yok.",
    store_get="Şuradan indir", store_dl="Şuradan indir", store_soon="Çok yakında",
    fact1="Hesap gerekmez", fact2="Reklam yok", fact3="15 dil",
    screens_h="Çalışırken gör", screens_sub="İlk kurulumdan tamamlanmış antrenman kartına kadar, IronLog kullanmak böyle görünüyor.",
    gallery_label="IronLog ekran görüntüleri, yana kaydır", shot_alt="IronLog ekran görüntüsü {n}/{total}",
    features_h="Antrenman tarzın için yapıldı", features_sub="Antrenmanını kaydetmek, takip etmek ve göstermek için ihtiyacın olan her şey, fazlası yok.",
    f1h="Saniyeler içinde kaydet", f1p="Set, tekrar, ağırlık, süre ve vücut ağırlığı egzersizleri tek dokunuşla. Seçiciler son değerlerinden başlar ve dinlenme sayacı hazır gelir.",
    f2h="Programın, senin tarzında", f2p="Kendi antrenman günlerini oluştur, egzersizleri süper setlerde birleştir ve yerleşik egzersiz kütüphanesini kullan ya da kendi özel egzersizlerini ekle. Her egzersize “BB Bench” gibi bir takma ad ver, senin söylediğin adla görünsün.",
    f3h="Gerçek ilerlemeyi gör", f3p="Kişisel rekorlar, haftalık eğilimler ve hacim grafikleri, ayrıca zaman içinde vücut ağırlığı ve ölçüler, hepsi tek bir takvim geçmişinde.",
    f4h="Paylaşım kartları", f4p="Biten her antrenmanı fotoğrafın, renklerin, yazı tipin ve düzenin olduğu, Instagram Hikâyesi tarzında bir karta dönüştür; paylaşmaya veya kaydetmeye hazır.",
    f5h="Tasarımdan gizli", f5p="Verilerin cihazında kalır. Hesap, giriş ya da bulut gerekmez; tek dosyayla yedekleme ve geri yükleme, ayrıca antrenman kaydının dışa aktarımı var.",
    f6h="Herkes için", f6p="15 dilde mevcut; Arapça ve Urduca için tam sağdan sola desteğiyle.",
    get_h="IronLog'u edin", get_sub="Telefonunun kamerasıyla kodu tara ya da bir düğmeye dokun.",
    android_p="Şimdi Google Play'de.", iphone_soon="App Store'a çok yakında geliyor.", iphone_live="Şimdi App Store'da.",
    qr_soon="Uygulama yayına girince QR kodu burada görünecek",
    qr_alt_play="Google Play'deki IronLog'a giden QR kodu", qr_alt_apple="App Store'daki IronLog'a giden QR kodu",
    foot_privacy="Gizlilik Politikası", foot_terms="Kullanım Koşulları", foot_guide="Kullanım Kılavuzu", foot_contact="İletişim",
    home_aria="IronLog ana sayfa", icon_alt="IronLog uygulama simgesi",
)

UR = dict(
    name="اردو", dir="rtl", html_lang="ur",
    title="IronLog: ورک آؤٹ ٹریکر",
    desc="IronLog ایک تیز اور آسان ورک آؤٹ ٹریکر ہے۔ ہر سیٹ سیکنڈوں میں لاگ کریں، اپنی طاقت ٹریک کریں اور ہر ورک آؤٹ کو شیئر کرنے کے قابل کارڈ میں بدلیں۔ بغیر اکاؤنٹ، بغیر اشتہارات، 15 زبانوں میں۔",
    og_desc="ہر سیٹ سیکنڈوں میں لاگ کریں، اپنی طاقت ٹریک کریں اور ہر کامیابی شیئر کریں۔ بغیر اکاؤنٹ، بغیر اشتہارات، 15 زبانوں میں۔",
    skip="مواد پر جائیں", nav_screens="اسکرینز", nav_features="خصوصیات", nav_get="ایپ حاصل کریں", lang_label="زبان",
    appid_sub="iPhone اور Android کے لیے ورک آؤٹ ٹریکر",
    h1a="ہر سیٹ لاگ کریں۔", h1b="ہر کامیابی شیئر کریں۔",
    lede="IronLog آپ کے ورک آؤٹس لاگ کرنے، طاقت ٹریک کرنے اور ہر سیشن کو شیئر کرنے کے لائق کارڈ میں بدلنے کا تیز اور آسان طریقہ ہے۔ اکاؤنٹ بنانے کی ضرورت نہیں، اور اشتہارات بھی رکاوٹ نہیں بنتے۔",
    store_get="یہاں سے حاصل کریں", store_dl="یہاں سے ڈاؤن لوڈ کریں", store_soon="جلد آ رہا ہے",
    fact1="اکاؤنٹ کی ضرورت نہیں", fact2="کوئی اشتہار نہیں", fact3="15 زبانیں",
    screens_h="اسے کام کرتے دیکھیں", screens_sub="پہلی سیٹنگ سے لے کر تیار ورک آؤٹ کارڈ تک، IronLog استعمال کرنا ایسا لگتا ہے۔",
    gallery_label="IronLog اسکرین شاٹس، سائیڈ میں اسکرول کریں", shot_alt="IronLog اسکرین شاٹ {n}/{total}",
    features_h="آپ کی ٹریننگ کے انداز کے لیے بنایا گیا", features_sub="اپنی ٹریننگ لاگ کرنے، فالو کرنے اور دکھانے کے لیے سب کچھ، اور کچھ فالتو نہیں۔",
    f1h="سیکنڈوں میں لاگ کریں", f1p="سیٹ، ریپس، وزن، دورانیہ اور باڈی ویٹ ورزشیں ایک ٹیپ میں۔ پکرز آپ کے پچھلے نمبروں سے شروع ہوتے ہیں، اور ریسٹ ٹائمر پہلے سے موجود ہے۔",
    f2h="آپ کا پروگرام، آپ کے انداز میں", f2p="اپنے ٹریننگ ڈے بنائیں، ورزشوں کو سپر سیٹ میں جوڑیں، اور بلٹ اِن ایکسرسائز لائبریری استعمال کریں یا اپنی کسٹم ورزشیں شامل کریں۔ کسی بھی ورزش کو اپنا عرفی نام دیں، جیسے “BB Bench”، تاکہ وہ اسی نام سے ملے جو آپ بولتے ہیں۔",
    f3h="حقیقی پیش رفت دیکھیں", f3p="ذاتی ریکارڈز، ہفتہ وار رجحانات اور والیوم چارٹس، ساتھ میں وقت کے ساتھ جسمانی وزن اور پیمائشیں، سب ایک کیلنڈر ہسٹری میں۔",
    f4h="شیئر کارڈز", f4p="کسی بھی مکمل ورک آؤٹ کو اپنی تصویر، رنگوں، فونٹ اور لے آؤٹ کے ساتھ انسٹاگرام اسٹوری طرز کے کارڈ میں بدلیں، جو شیئر یا محفوظ کرنے کے لیے تیار ہو۔",
    f5h="ڈیزائن ہی سے نجی", f5p="آپ کا ڈیٹا آپ کے آلے پر رہتا ہے۔ اکاؤنٹ، لاگ اِن یا کلاؤڈ کی ضرورت نہیں، ایک فائل میں بیک اپ اور ریسٹور، اور ورک آؤٹ لاگ ایکسپورٹ کی سہولت کے ساتھ۔",
    f6h="سب کے لیے", f6p="15 زبانوں میں دستیاب، عربی اور اردو کے لیے دائیں سے بائیں لکھنے کی مکمل سپورٹ کے ساتھ۔",
    get_h="IronLog حاصل کریں", get_sub="اپنے فون کے کیمرے سے کوڈ اسکین کریں، یا کسی بٹن پر ٹیپ کریں۔",
    android_p="اب Google Play پر دستیاب ہے۔", iphone_soon="App Store پر جلد آ رہا ہے۔", iphone_live="اب App Store پر دستیاب ہے۔",
    qr_soon="ایپ لائیو ہونے پر QR کوڈ یہاں نظر آئے گا",
    qr_alt_play="Google Play پر IronLog کا QR کوڈ", qr_alt_apple="App Store پر IronLog کا QR کوڈ",
    foot_privacy="رازداری کی پالیسی", foot_terms="استعمال کی شرائط", foot_guide="یوزر گائیڈ", foot_contact="رابطہ کریں",
    home_aria="IronLog ہوم", icon_alt="IronLog ایپ آئیکن",
)

ZH = dict(
    name="简体中文", dir="ltr", html_lang="zh-Hans",
    title="IronLog: 训练记录追踪器",
    desc="IronLog 是一款快速、简洁的训练记录应用。几秒钟记录每一组，追踪你的力量，并把每次训练变成可分享的卡片。无需账号，没有广告，支持 15 种语言。",
    og_desc="几秒钟记录每一组，追踪你的力量，分享每一次成果。无需账号，没有广告，支持 15 种语言。",
    skip="跳到正文", nav_screens="界面", nav_features="功能", nav_get="获取应用", lang_label="语言",
    appid_sub="适用于 iPhone 和 Android 的训练记录应用",
    h1a="记录每一组。", h1b="分享每一次成果。",
    lede="IronLog 是记录训练、追踪力量，并把每次训练变成值得分享的卡片的快捷方式。无需创建账号，也没有广告打扰。",
    store_get="获取自", store_dl="下载自", store_soon="即将登陆",
    fact1="无需账号", fact2="没有广告", fact3="15 种语言",
    screens_h="看看实际效果", screens_sub="从首次设置到完成的训练卡片，这就是使用 IronLog 的样子。",
    gallery_label="IronLog 截图，左右滑动", shot_alt="IronLog 截图 {n}/{total}",
    features_h="为你的训练方式而生", features_sub="记录、跟进和展示训练所需的一切，没有多余的东西。",
    f1h="几秒钟完成记录", f1p="组数、次数、重量、时长和自重动作，一键即可记录。选择器从你上次的数值开始，并内置休息计时器。",
    f2h="你的计划，你做主", f2p="创建自己的训练日，把动作组成超级组，使用内置动作库或添加自定义动作。可以给任何动作设置别名，比如“BB Bench”，用你习惯的叫法称呼它。",
    f3h="看见真实进步", f3p="个人纪录、每周趋势和训练量图表，外加体重和身体围度的长期变化，全部整合在日历历史里。",
    f4h="分享卡片", f4p="把任何一次完成的训练变成带有你的照片、颜色、字体和版式的卡片，采用 Instagram 快拍风格，随时可分享或保存。",
    f5h="隐私为先", f5p="你的数据只保存在你的设备上。无需账号、登录或云端，一个文件即可备份和恢复，还可导出训练记录。",
    f6h="为每个人而做", f6p="支持 15 种语言，并完整支持阿拉伯语和乌尔都语的从右到左显示。",
    get_h="获取 IronLog", get_sub="用手机相机扫描二维码，或点击按钮。",
    android_p="现已登陆 Google Play。", iphone_soon="即将登陆 App Store。", iphone_live="现已登陆 App Store。",
    qr_soon="应用上线后，这里会显示二维码",
    qr_alt_play="指向 Google Play 上 IronLog 的二维码", qr_alt_apple="指向 App Store 上 IronLog 的二维码",
    foot_privacy="隐私政策", foot_terms="使用条款", foot_guide="用户指南", foot_contact="联系我们",
    home_aria="IronLog 首页", icon_alt="IronLog 应用图标",
)

# site code -> (strings, screenshot folder in the main repo's headline-v2 set)
LANGS = {
    "en": (EN, "en-US"), "ar": (AR, "ar"), "bn": (BN, "bn-BD"), "de": (DE, "de-DE"), "es": (ES, "es-ES"),
    "fr": (FR, "fr-FR"), "hi": (HI, "hi-IN"), "id": (ID, "id"), "ja": (JA, "ja-JP"), "ko": (KO, "ko-KR"),
    "pt": (PT, "pt-BR"), "ru": (RU, "ru-RU"), "tr": (TR, "tr-TR"), "ur": (UR, "ur"), "zh": (ZH, "zh-CN"),
}
